import { Geist, Geist_Mono } from 'next/font/google';

import type { Metadata } from 'next';

import { ThemeProvider } from '@/components/providers/theme-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} from-background via-muted/40 to-background h-screen w-screen bg-gradient-to-br antialiased dark:from-[#071323] dark:via-[#0b1e36] dark:to-[#0f2745]`}
      >
        <ThemeProvider>{children} </ThemeProvider>
      </body>
    </html>
  );
}
