import { Geist, Geist_Mono } from 'next/font/google';

import { TanStackDevtools } from '@tanstack/react-devtools';
import { FormDevtoolsPanel } from '@tanstack/react-form-devtools';
import type { Metadata } from 'next';

import { cn } from '@/lib/utils';

import Providers from './providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            geistSans.variable,
            geistMono.variable,
            'antialiased',
            'h-screen',
          )}
        >
          <Providers>{children}</Providers>
        </body>
      </html>
      <TanStackDevtools
        plugins={[
          {
            name: 'TanStack Form Panel',
            render: <FormDevtoolsPanel />,
            defaultOpen: true,
          },
        ]}
      />
    </>
  );
}
